kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.global.processor.kafka.kafkaBridge.routeName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  host: {{ include "processor-chart.buildKafkaBridgeHostUrl" . }}
  to:
    kind: Service
    name: {{ .Values.kafka.kafkaBridge.bridgeName }}-bridge-service
    weight: 100
  port:
    targetPort: {{ .Values.kafka.kafkaBridge.httpPort }}