apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.kafka.kafkaCluster.clusterName }}
  name: {{ .Values.kafka.kafkaUser.userName }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  authentication:
    type: {{ .Values.kafka.kafkaUser.authenticationType }}
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: my-topic
          patternType: literal
          type: topic
        type: allow
      - host: '*'
        operation: All
        resource:
          name: daboogie-consumer-group
          patternType: literal
          type: group
        type: allow
    type: {{ .Values.kafka.kafkaUser.authorizationType }}