# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: abb-poc-ui
replicaCount: 3

image:
  repository: quay.io/ecosystem-appeng/abb-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

port: 
  containerPort: 3000
  protocol: TCP

service:
  port: 80

engineering:
  serviceName: abb-engineering
  servicePort: 10000