apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.port.containerPort }}
              protocol: {{ .Values.port.protocol }}
          env:
            - name: PROCESSOR_SERVICE
              value: 'ws://processor-service.abb-poc.svc.cluster.local:8080'
            - name: ENGINEERING_SERVICE
              value: 'http://abb-engineering.abb-poc.svc.cluster.local:10000'