apiVersion: policy/v1beta1
kind: PodDisruptiveBudget
metadata:
  name: {{ include "processor-chart.fullname" . }}
  namespace: {{.Values.namespace}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: processor