apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "processor-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: processor