apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: processor
  ports:
    - name: http
      port: 80
      targetPort: 80