# Default values for processor-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
namespace: abb-poc
image: quay.io/ecosystem-appeng/abb-poc-processor
image_tag: 1.0.1
kafka_bootstrap_server: my-cluster-kafka-bootstrap:9095
kafka_jaas_config: ???
