apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.ports.protocol }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.containerPort }}